#!/bin/sh

# Program: Install
# Purpose: Install script for the WK Silver Book
# Assumptions: that this script is run from the directory which contains it

#
#  If the MGICONFIG environment variable does not have a local override,
#  use the default "live" settings.
#
if [ "${MGICONFIG}" = "" ]
then
    MGICONFIG=/usr/local/mgi/live/mgiconfig
    export MGICONFIG
fi

. ${MGICONFIG}/master.config.sh

###--- Global Variables ---###

TOP=`pwd`
CONFIGURATION=Configuration

#####################################################################
###  MAIN LOGIC
#####################################################################

###--- Config setup and reading of non-include parameters --------###
if test ! -r $CONFIGURATION
then
    echo "Missing configuration file.  Please create $CONFIGURATION."
    exit 1
fi

exec 4<&0
exec < $CONFIGURATION
while read name value junk
do
    case "$name" in
        LIBDIRS)
            LIBDIRS=$value;;
        CONFIGPATH)
            CONFIGPATH=$value;;
    esac
done
exec 0<&4

###--- Add link to configuration python executable ---------------###
if [ -h Configuration.pyc ]; then
    rm Configuration.pyc
fi
ln -s $CONFIGPATH Configuration.pyc

if [ -h python ]; then
    rm python
fi
ln -s $PYTHON python

###--- Generate the include directory ----------------------------###
gen_includes
chmod -f 750 Configuration Configuration.defaults gen_includes HISTORY include Install www
chgrp -f www Configuration Configuration.defaults gen_includes HISTORY include Install www

