#!/bin/sh

#####################################################################
###  Variable definitions (edit as needed)

TOP=`pwd`
CONFIGURATION=Configuration


#####################################################################
### includeLinker function - create a ../include symbolic link in 
### the current directory and in each subdirectory (recursively)

includeLinker() {
	# do this directory
	if [ -h include ]; then
		rm include
	fi
	if [ ! -d include ]; then
		echo "Linking to include/ in `pwd`"
		ln -s ../include include
	fi

	# then do all subdirectories recursively
	for name in `ls`
	do
		if [ -d $name ]; then
			if [ $name != include ]; then
				if [ $name != CVS ]; then
					cd $name
					(includeLinker)
					cd ..
				fi
			fi
		fi
	done
	}



#####################################################################
### Read variables from the config file
if test ! -r $CONFIGURATION
then
	echo "Missing configuration file.  Please create $CONFIGURATION."
	exit 1
fi

exec 4<&0
exec < $CONFIGURATION
while read name value junk
do
	case "$name" in
		LIBDIRS)
			LIBDIRS=$value;;
		CONFIGPATH)
			CONFIGPATH=$value;;
		PYTHONPATH)
			PYTHONPATH=$value;;
	esac
done
exec 0<&4

#####################################################################
### Add link to compiled configuration python module 
### and python executable
if [ -h Configuration.pyc ]; then
	rm Configuration.pyc
fi
ln -s $CONFIGPATH Configuration.pyc

if [ -h python ]; then
	rm python
fi
ln -s $PYTHONPATH python

#####################################################################
### Un"tar" the www book files, create include directory, generate
### the needed include files, and set permissions for this directory

tar xvfp book.tar

if [ -d www ]; then
	cd www
	if [ ! -d include ]; then
		echo "Making 'include' directory in `pwd`"
		mkdir include
	fi
	
	cd $TOP
	
	gen_includes
	
	includeLinker
	
	mv rosetta_report.cgi ./www/rosetta_report.cgi
	
	chmod 750 www
	chgrp www www

fi

#
# Warranty Disclaimer and Copyright Notice
# 
#  THE JACKSON LABORATORY MAKES NO REPRESENTATION ABOUT THE SUITABILITY OR 
#  ACCURACY OF THIS SOFTWARE OR DATA FOR ANY PURPOSE, AND MAKES NO WARRANTIES, 
#  EITHER EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY AND FITNESS FOR A 
#  PARTICULAR PURPOSE OR THAT THE USE OF THIS SOFTWARE OR DATA WILL NOT 
#  INFRINGE ANY THIRD PARTY PATENTS, COPYRIGHTS, TRADEMARKS, OR OTHER RIGHTS.  
#  THE SOFTWARE AND DATA ARE PROVIDED "AS IS".
# 
#  This software and data are provided to enhance knowledge and encourage 
#  progress in the scientific community and are to be used only for research 
#  and educational purposes.  Any reproduction or use for commercial purpose 
#  is prohibited without the prior express written permission of the Jackson 
#  Laboratory.
# 
# Copyright © 1996, 1999, 2002 by The Jackson Laboratory
# All Rights Reserved
#

